global:
  slack_api_url: https://hooks.slack.com/services/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
route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alexanrd_orel'